### PR TITLE
Set mail from address when sending bounce emails.

### PR DESCRIPTION
**Pull request by wjywbs**

### CODE REVIEW

**Comment by foxcpp** [comment]
[RFC 5321 Section 6.1](https://tools.ietf.org/html/rfc5321#section-6.1) says DSNs **MUST** be sent using null (<>) reverse path in envelope. What is the reason for standard deviation?

**Comment by foxcpp** [comment]
Most importantly, null reverse path has a special meaning is that DSNs MUST NOT be generated for messages sent with it.  This prevents infinite loop of DSNs sent in response to other DSNs.

**Comment by wjywbs** [comment]
Sorry for no explanation. maddy generated error "address: missing at-sign" and "Malformed sender address" when sending DSNs with empty from address. I see that other providers also send delivery failure reports using MAILER-DAEMON@autogenerated_msg_domain. I'll read the RFC.

**Comment by foxcpp** [comment]
That looks like a bug in maddy. How your config looks like?

**Comment by wjywbs** [comment]
```
queue outbound_queue {
    target remote {
        limits &outbound_limits
        mx_auth &outbound_auth
    }

    autogenerated_msg_domain $(primary_domain)
    bounce {
        destination some.other.domain.not.local.domains {  <- dsn fails to send
            check &outbound_checks
            modify &outbound_modifiers
            deliver_to &outbound_queue
        }
        default_destination {
            reject 550 5.0.0 "Refusing to send DSNs to non-local addresses"
        }
    }
}
```

**Comment by wjywbs** [comment]
Sorry, I pasted the wrong config. I updated the previous config.

**Comment by foxcpp** [comment]
Aha, so the likely source of error is this call: https://github.com/foxcpp/maddy/blob/64c91fcc7cc8d546c4de01768158e0834d77228c/internal/target/remote/remote.go#L196

The proper solution is to patch this call to handle empty return path correctly (likely by using an empty domain string for TakeMsg call below).

P.S. I hope you understand concerns outlined in https://foxcpp.dev/maddy/tutorials/alias-to-remote/ about sending bounce messages back to arbitrary addresses. This setup is very prone to creating [collateral spam](https://en.wikipedia.org/wiki/Backscatter_(email)).

**Comment by wjywbs** [comment]
Yes, I'm only allowing to send bounces to pre-defined domains "some.other.domain". The default_destination still rejects to send DSNs.

**Comment by foxcpp** [comment]
@wjywbs do you intend to write a patch to fix the problem described above?

**Comment by wjywbs** [comment]
No, I'm not sure how to fix it.

**Comment by foxcpp** [comment]
6466eaa4b1c8643ef050e1fef5cf938f4c4f82ef is the fix for your problem.

**Pull request closed without merging**
