### PR TITLE
Fixed misspells in README.md

### PR DESCRIPTION
**Pull request by Avamander**
It would be also nice to specify how to set the `nosqlite3` tag for those not familiar with go.

### CODE REVIEW

**Comment by emersion** [comment]
>It would be also nice to specify how to set the nosqlite3 tag for those not familiar with go.

Feel free to send a patch

**Comment by emersion** [comment]
Thanks!

**Comment by Avamander** [comment]
@emersion I wish I'd knew how to set it :D

**Comment by Avamander** [comment]
@emersion, how would one go about and set the `nosqlite3` tag? I tried googling this but I got no results and I'm sure I'm not the only one who is wondering :P

**Comment by emersion** [comment]
```
go build -tags 'tag1 tag2'
```

**Pull request merged**
